---
# ADD SINGLE VLAN

- name: VLAN Provisioning
  hosts: n911
  connection: local
  gather_facts: true

  vars:
    nxapi:
      host: "{{ host }}"
      username: ""
      password: ""
      transport: nxapi
      use_ssl: yes
      validate_certs: no
      port: 8181

  tasks:

  - name: Create checkpoint file
    nxos_rollback:
      checkpoint_file: "{{ ansible_date_time.iso8601_basic_short }}.cfg"
      provider: "{{ nxapi }}"
    register: result

  - debug: var=result
  
  - name: Add VLAN 
    nxos_vlan:
      vlan_id: 70
      name: test_70
      state: present
      provider: "{{ nxapi }}"
    when: result|success
    notify: write

  handlers:
  - name: write
    nxos_config:
      provider: "{{ nxapi }}"
      commands: "copy running-config startup-config"

  - debug: "msg='End of add single VLAN'"
